runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /crossmodepic\.jpg
  static_files: crossmodepic.jpg
  upload: crossmodepic\.jpg

- url: /bootstrap
  static_dir: bootstrap
  
- url: /register
  static_dir: register
 
- url: /failpage
  static_dir: failpage

- url: /customerpage
  static_dir: customerpage

- url: /eyeshowpage
  static_dir: eyeshowpage
  
- url: /forgetpassword
  static_dir: forgetpassword
  
- url: /login
  static_dir: login
  
- url: /qrcode
  static_dir: qrcode
  
- url: /price
  static_dir: price
  
- url: /.*
  script: eyeshow.app


  
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]